name: gofoodie
description: GoFoodie Mobile Application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_bloc: ^6.1.2
  equatable: ^1.2.6
  get_it: ^5.0.6
  dartz: ^0.9.2
  page_transition: ^1.1.7+6
  fluttertoast: ^7.1.8
  easy_localization:
  dio: ^3.0.10
  data_connection_checker: ^0.3.4
  hive: ^1.4.4+1
  path_provider: ^1.6.27
  flutter_secure_storage: ^3.3.5
  cached_network_image: ^2.5.0
  vibration: ^1.7.3
  percent_indicator:
  flutter_rating_bar:
  rxdart:
  flutter_google_places:
  geolocator: 
  geocoder: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lang/en-US.json
    - assets/images/splash_screen.jpg
    - assets/images/food.png
    - assets/images/icon.jpg
    - assets/images/loading.gif
    - assets/images/vendor_backgound.png
    - assets/images/no_image.jpg
    - assets/images/drawer.jpg
    - assets/images/user-icon.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
